name: 'Setup solc'
description: 'Install the Solidity compiler'
branding:
  icon: download
  color: blue
inputs:
  version:
    description: 'Version to be installed as `solc`'
    default: ''
  versions:
    description: 'Comma-separated list of versions to be installed as `solc-v<ver>'
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'